version: '3.3'

services:
  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_password
  init_db:
    build: ./init_db
    depends_on:
      - db
    secrets:
      - postgres_password
  api:
    build: ./api
    ports:
      - 443:443
  web:
    build: ./web
    ports:
      - 80:80

volumes:
  postgres:

secrets:
  postgres_password:
    file: secrets/postgres_password
